### ISSUE TITLE
開発システム

### ISSUE THREAD

**Issue by kaizen-nagoya** [nagonagoya/Scheduler#18]
現在は、同じ場所で作業している。
将来、離れた場所で作業しても、データ、プログラムを相互に reviewして、より良いシステム開発ができるグループでいたい。
オープンソースにも参加することにより、技術力の向上と、情報交換能力の向上を図る。

1. github
1.１ githubを利用する
1,2 wikiにかけるようになる。
1.3 issuesを発行する
1.4 他の人があげたソースを試験できる

1.４は  dockerを利用することによって確率をあげたい。

２ dockerを利用する
2.1 同じ環境で、同じ試験の再現性を確認する。
2.2 異なる版の環境での試験を容易に用意する
2.3 将来の出荷する版が何が良いかを検討する

**Comment by hotmilk66** [comment]
１、２ともに完了
