### ISSUE TITLE
dockerでApacheの起動方法の仕様が決めれていない。

### ISSUE THREAD

**Issue by kaizen-nagoya** [nagonagoya/Scheduler#2]
dockerには公式httpdがある。
https://hub.docker.com/_/httpd/
docker pull http
導入はできた。
docker run -it fb2f3851a971  /bin/bash
-bash: $: command not found
コマンドで入り方がわからない。
現状：
サーバを立ち上げるだけであれば、コマンドはいらないかもしれない。
Raspbiandeコマンドで実行する内容と同じ内容をdockerでも試験したい。

**Comment by enndou** [comment]
--------------------------------------------------------------------------------------------+
#!/bin/sh
#Dockerを立ち上げてから実行する。
#~/docker/php70-apache/wwwにコンテンツを配置

docker run -d -p 80:80 -v ~/docker/php70-apache/www:/var/www/html --name php70-apache php:7.0-apache
git clone https://github.com/nagonagoya/Scheduler.git
cp Scheduler/* ~/docker/php70-apache/www
mkdir ~/docker/php70-apache/www/css
mkdir ~/docker/php70-apache/www/favicon
mkdir ~/docker/php70-apache/www/html
mkdir ~/docker/php70-apache/www/js
cp Scheduler/css/* ~/docker/php70-apache/www/css
cp Scheduler/favicon/* ~/docker/php70-apache/www/favicon
cp Scheduler/html/* ~/docker/php70-apache/www/html
cp Scheduler/js/* ~/docker/php70-apache/www/js
-------------------------------------------------------------------------------------------+

ローカルでのDockerのApache+PHP7.0の起動方法。
一応これで、起動する。
raspberry piでのシェルスクリプトも挑戦中。
次は、実際の公開するサーバとraspberry piのシェルスクリプト
についてissueに掲載予定。
