### ISSUE TITLE
用語の選択基準

### ISSUE THREAD

**Issue by kaizen-nagoya** [nagonagoya/Scheduler#24]
１　短い用語を使う
２　略号は文書にfull spell lstをつける
３　カタカナ語は原則利用しない。漢字の言葉か原語(alphabet等）で表現する
４　プログラミング言語記述、HTML記述とそれ以外を区分し、予約語は変数名、略号で用いない（プログラム以外でも）
５　類似の語があれば、用語一覧に掲載する。できれば包含関係（上下関係）を記載する。

**Comment by hotmilk66** [comment]
＞２　略号は文書にfull spell lstをつける
→一部略語を使っていたと思います。今後のコード改修で、
フルスペルに修正するか略語一覧を掲載します。
