### ISSUE TITLE
新しいIssueの上げ方

### ISSUE THREAD

**Issue by kaizen-nagoya** [nagonagoya/Scheduler#27]
新しいIssueの上げ方の規則が決まっていない。

１　issueをざっと読む。

関連するものは、そちらに追記、コメントする

２　該当するものがなければ、new issueをクリックする。

**Comment by nagonagoya** [comment]
了解しました。

**Comment by kaizen-nagoya** [comment]
コメントの仕方についての規則はまだ決まっていません。

**Comment by kaizen-nagoya** [comment]
新しいissueをあげてもらえたためcloseします。
