### ISSUE TITLE
Docker hubへの掲載

### ISSUE THREAD

**Issue by kaizen-nagoya** [nagonagoya/Scheduler#42]
Docker hubへの掲載
https://hub.docker.com

1 手順
http://docs.docker.jp/windows/step_five.html

2掲載する対象
Docker Image
Dockerfileは作る必要はない。

ライセンス関係の記述に注意し、人が作成したイメージを改変したものをあげても良い。
自分が作成したイメージを保存して、あげても良い。

Dockerfile, コマンドスクリプトなども用意しておくと、
自分の作業のうち、無駄、無理などを訂正してもらえるかもしれない。

**Comment by enndou** [comment]
docker hub にイメージを掲載しました。
dockerを起動した状態で、

$ docker pull junendocreater/php
 
でイメージファイルをpullできます。
最初、タグを"7.0-apache"にしないとだめだと勘違いしていましたが、
"latest"つまり最新にしても大丈夫でした。
これから、フレームワークを抽象化していくようなことがあれば、
docker fileにしてdocker hub に掲載していきます。
