### ISSUE TITLE
githubを経由しない場合のWebサーバへのデータ、プログラムのUpload方法

### ISSUE THREAD

**Issue by kaizen-nagoya** [nagonagoya/Scheduler#5]
作成したデータ、プログラムを、３つの想定するWebサーバに掲載するに当たってUploadする方法。

採用しない予定の方法
NFS：Network File system、セキュリティ上、同室内での実験では便利さを測定するために試用するが、実用的には用いない。
FTP: File Transfer Protocol、ファイルの暗号化をしていない段階では用いない。

採用予定の方法
SFTP

**Comment by enndou** [comment]
#?/bin/sh
#コンテンツはカレントディレクトリにあると想定

mv Scheduler/* ~/docker/nagoya/www/Scheduler
docker run -d -p 80:80 -v ~/docker/nagoya/www/Scheduler:/var/www/html --name nagoya junendocreater/php

で解決。
