### ISSUE TITLE
WebサーバソフトはApacheでいいか。

### ISSUE THREAD

**Issue by kaizen-nagoya** [nagonagoya/Scheduler#7]
当初の作業としては、シェアが一位で、情報が多いApacheを検討対象としている。
nginxはこれまでは順調に伸びている。比較候補として記載。
https://news.mynavi.jp/article/20180501-623638/

**Comment by hotmilk66** [comment]
Apacheとnginxの比較記事がありました。
https://qiita.com/pink/items/7709218310b5cf11eabe
まとめると
　　↓
nginx：処理が軽く、大量のリクエストを処理するのに向いている
Apache：CPUリソースがたくさん必要な処理に向いている

実際にnginxのイメージをpullして試してみましたが問題なさそうです。

このサービスが大量に利用されることになった場合にはnginxの方が向いている気がします。
現状ではApacheで十分だと考えます。
